name: CI - App Controle Despesas

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Código
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # ou a versão do seu projeto

      - name: Instalar Dependências
        run: npm install

      - name: Buildar Projeto
        run: npm run build

      # (Opcional) Executar testes automáticos
      # - name: Rodar Testes
      #   run: npm test

      # (Opcional) Deploy em outro servidor ou plataforma
      # - name: Deploy
      #   run: ./scripts/deploy.sh  # ou outro método
