name: CI - App Controle Despesas

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: app_controle_despesas  # <- Mudamos aqui!

    steps:
      - name: Checkout Código
        uses: actions/checkout@v4   # <-- sem path aqui!

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar Dependências
        run: npm install

      - name: Buildar Projeto
        run: npm run build
