name: CI - App Controle Despesas

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: .  # <- Garante que vai rodar da raiz do repositório

    steps:
      - name: Checkout Código
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # ou a versão que você usa

      - name: Instalar Dependências
        run: npm install

      - name: Buildar Projeto
        run: npm run build

      # (Opcional) Rodar Testes
      # - name: Rodar Testes
      #   run: npm test
